# Development venv for dinosar development
name: dinosar-dev
channels:
  - conda-forge
dependencies:
  - python=3.8
  - geopandas
  - msgpack-python
  - poetry
  - poetry-dynamic-versioning
  - pyyaml
