# Run tests on different OS/Python combinations
name: Conda-Matrix

on:
  pull_request:
    branches: main

jobs:
  quality-control:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    # NOTE: this isn't a comprehensive spellcheck, just common typos
    - name: Spellcheck
      uses: codespell-project/actions-codespell@master
      with:
        check_filenames: true
        check_hidden: true
        only_warn: true

  conda:
    name: ${{ matrix.os }}-${{ matrix.CONDA_ENV }}-build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        CONDA_ENV: [3.7, 3.8, 3.9]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles(${{ matrix.CONDA_ENV }}.yml) }}

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          environment-file: ci/environment-dev-py${{ matrix.CONDA_ENV }}.yml
          activate-environment: dinosar
          use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!

      - name: Install Dinosar From Latest Commit
        run: |
          conda --version
          python -m pip install .
          conda list

      - name: Run PyTest
        run: |
          pytest  -o markers=network -m "not network" --verbose --cov=dinosar --cov-report=xml
